### ISSUE TITLE
Html export svg assets size

### ISSUE THREAD

**Issue by fr32c** [davidderaedt/Illustrator-Layer-Exporter#2]
I know the html export is a Work in Progress, so, it's a good start, and can be animated inside Edge Animate, but so far it doesn't seem to remember the size of the svg items they are all huge !

![ai-layexp-an-svg](https://cloud.githubusercontent.com/assets/2315207/2559795/cee9d8e0-b78c-11e3-9d70-1fb904fbb85f.png)

**Comment by davidderaedt** [comment]
Fixed in 1.5
