### ISSUE TITLE
Html export png - replace images - create symbols

### ISSUE THREAD

**Issue by fr32c** [davidderaedt/Illustrator-Layer-Exporter#3]
This is an Animate problem, but i realize this while testing LE 1.4

When you use an .html file in Animate, it's not possible to swap images with something else, since they're defined as <img> inside the html file/DOM.

We also loose a lot of the interactivity available in Animate, since an image itself cannot be grouped or put inside a symbol (with its own timeline and interactivity).

This advocates in favor of a distinct .html AND .an export :)

**Comment by davidderaedt** [comment]
Thanks for the feedback. I'll have to investigate if those limitations are implied for any HTML import in animate or because of LE's own formatting.

**Comment by fr32c** [comment]
see this FR on the generator side, a bit more details : https://github.com/adobe-photoshop/generator-assets/issues/206

**Comment by davidderaedt** [comment]
This is indeed a limitation on the Edge Animate side. Choosing the "Import to Edge Animate" option fixes it.
